compilation:
  cloud_properties:
    instance_type: m1.medium
  network: cf1
  reuse_compilation_vms: true
  workers: 6
director_uuid: DIRECTOR_UUID
jobs:
- instances: 1
  name: consul_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.12
  persistent_disk: 1024
  properties:
    consul:
      agent:
        mode: server
    metron_agent:
      zone: z1
  resource_pool: small_z1
  templates:
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: true
- instances: 0
  name: consul_z2
  networks:
  - name: cf2
    static_ips: []
  persistent_disk: 1024
  properties:
    consul:
      agent:
        mode: server
    metron_agent:
      zone: z2
  resource_pool: small_z2
  templates:
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
    serial: true
- default_networks:
  - name: cf1
    static_ips: null
  instances: 1
  name: ha_proxy_z1
  networks:
  - name: floating
    static_ips:
    - 0.0.0.0
  - default: null
    name: cf1
    static_ips:
    - 0.0.0.0
  properties:
    ha_proxy:
      disable_http: false
      ssl_ciphers: null
      ssl_pem: null
    metron_agent:
      zone: z1
    router:
      servers:
        z1:
        - 0.0.0.5
        z2: []
  resource_pool: router_z1
  templates:
  - name: haproxy
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  update: {}
- instances: 1
  name: nats_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.2
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: nats
    release: cf
  - name: nats_stream_forwarder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 0
  name: nats_z2
  networks:
  - name: cf2
    static_ips: []
  properties:
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: nats
    release: cf
  - name: nats_stream_forwarder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: etcd_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.8
  persistent_disk: 10024
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: etcd
    release: cf
  - name: etcd_metrics_server
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
- instances: 0
  name: etcd_z2
  networks:
  - name: cf2
    static_ips: []
  persistent_disk: 10024
  properties:
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: etcd
    release: cf
  - name: etcd_metrics_server
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
- instances: 1
  name: stats_z1
  networks:
  - name: cf1
  properties:
    metron_agent:
      zone: z1
  resource_pool: small_z1
  templates:
  - name: collector
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: nfs_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.3
  persistent_disk: 102400
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: debian_nfs_server
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: postgres_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.4
  persistent_disk: 4096
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: postgres
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: uaa_z1
  networks:
  - name: cf1
  properties:
    consul:
      agent:
        services:
          uaa: {}
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: uaa
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  update: {}
- instances: 0
  name: uaa_z2
  networks:
  - name: cf2
  properties:
    consul:
      agent:
        services:
          uaa: {}
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: uaa
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  update: {}
- instances: 1
  name: api_z1
  networks:
  - name: cf1
  persistent_disk: 0
  properties:
    consul:
      agent:
        services:
          cloud_controller_ng: {}
          routing-api: {}
    metron_agent:
      zone: z1
    nfs_server:
      address: 0.0.0.3
      allow_from_entries:
      - null
      - null
      share: null
  resource_pool: large_z1
  templates:
  - name: cloud_controller_ng
    release: cf
  - name: routing-api
    release: cf
  - name: metron_agent
    release: cf
  - name: statsd-injector
    release: cf
  - name: consul_agent
    release: cf
  - name: nfs_mounter
    release: cf
  update: {}
- instances: 0
  name: api_z2
  networks:
  - name: cf2
  persistent_disk: 0
  properties:
    consul:
      agent:
        services:
          cloud_controller_ng: {}
          routing-api: {}
    metron_agent:
      zone: z2
    nfs_server:
      address: 0.0.0.3
      allow_from_entries:
      - null
      - null
      share: null
  resource_pool: large_z2
  templates:
  - name: cloud_controller_ng
    release: cf
  - name: routing-api
    release: cf
  - name: metron_agent
    release: cf
  - name: statsd-injector
    release: cf
  - name: consul_agent
    release: cf
  - name: nfs_mounter
    release: cf
  update: {}
- instances: 1
  name: clock_global
  networks:
  - name: cf1
  persistent_disk: 0
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: cloud_controller_clock
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: api_worker_z1
  networks:
  - name: cf1
  persistent_disk: 0
  properties:
    metron_agent:
      zone: z1
    nfs_server:
      address: 0.0.0.3
      allow_from_entries:
      - null
      - null
      share: null
  resource_pool: small_z1
  templates:
  - name: cloud_controller_worker
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  - name: nfs_mounter
    release: cf
  update: {}
- instances: 0
  name: api_worker_z2
  networks:
  - name: cf2
  persistent_disk: 0
  properties:
    metron_agent:
      zone: z2
    nfs_server:
      address: 0.0.0.3
      allow_from_entries:
      - null
      - null
      share: null
  resource_pool: small_z2
  templates:
  - name: cloud_controller_worker
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  - name: nfs_mounter
    release: cf
  update: {}
- instances: 1
  name: hm9000_z1
  networks:
  - name: cf1
  properties:
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: hm9000
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 0
  name: hm9000_z2
  networks:
  - name: cf2
  properties:
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: hm9000
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: runner_z1
  networks:
  - name: cf1
    static_ips: null
  properties:
    dea_next:
      zone: z1
    metron_agent:
      zone: z1
  resource_pool: runner_z1
  templates:
  - name: dea_next
    release: cf
  - name: dea_logging_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
- instances: 0
  name: runner_z2
  networks:
  - name: cf2
    static_ips: null
  properties:
    dea_next:
      zone: z2
    metron_agent:
      zone: z2
  resource_pool: runner_z2
  templates:
  - name: dea_next
    release: cf
  - name: dea_logging_agent
    release: cf
  - name: metron_agent
    release: cf
  update:
    max_in_flight: 1
- instances: 0
  name: loggregator_z1
  networks:
  - name: cf1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: doppler
    release: cf
  - name: syslog_drain_binder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 0
  name: loggregator_z2
  networks:
  - name: cf2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: doppler
    release: cf
  - name: syslog_drain_binder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: doppler_z1
  networks:
  - name: cf1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1
  resource_pool: medium_z1
  templates:
  - name: doppler
    release: cf
  - name: syslog_drain_binder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 0
  name: doppler_z2
  networks:
  - name: cf2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2
  resource_pool: medium_z2
  templates:
  - name: doppler
    release: cf
  - name: syslog_drain_binder
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: loggregator_trafficcontroller_z1
  networks:
  - name: cf1
  properties:
    metron_agent:
      zone: z1
    traffic_controller:
      zone: z1
  resource_pool: small_z1
  templates:
  - name: loggregator_trafficcontroller
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 0
  name: loggregator_trafficcontroller_z2
  networks:
  - name: cf2
  properties:
    metron_agent:
      zone: z2
    traffic_controller:
      zone: z2
  resource_pool: small_z2
  templates:
  - name: loggregator_trafficcontroller
    release: cf
  - name: metron_agent
    release: cf
  update: {}
- instances: 1
  name: router_z1
  networks:
  - name: cf1
    static_ips:
    - 0.0.0.5
  properties:
    consul:
      agent:
        services:
          gorouter: {}
    metron_agent:
      zone: z1
  resource_pool: router_z1
  templates:
  - name: gorouter
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  update: {}
- instances: 0
  name: router_z2
  networks:
  - name: cf2
    static_ips: []
  properties:
    consul:
      agent:
        services:
          gorouter: {}
    metron_agent:
      zone: z2
  resource_pool: router_z2
  templates:
  - name: gorouter
    release: cf
  - name: metron_agent
    release: cf
  - name: consul_agent
    release: cf
  update: {}
- instances: 1
  lifecycle: errand
  name: acceptance_tests
  networks:
  - name: cf1
  resource_pool: small_errand
  templates:
  - name: acceptance-tests
    release: cf
- instances: 0
  lifecycle: errand
  name: smoke_tests
  networks:
  - name: cf1
  properties: {}
  resource_pool: small_errand
  templates:
  - name: smoke-tests
    release: cf
meta:
  environment: null
  releases:
  - name: cf
    version: latest
name: null
networks:
- name: cf1
  subnets:
  - cloud_properties: null
    static:
    - 0.0.0.0 - 0.0.0.26
properties:
  cc:
    app_events:
      cutoff_age_in_days: 31
    droplets:
      droplet_directory_key: the_key
  has:
    opinion: this is an opinion
releases:
- name: cf
  version: latest
resource_pools:
- cloud_properties:
    instance_type: m1.small
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: small_z1
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.small
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: small_z2
  network: cf2
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.medium
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: medium_z1
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.medium
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: medium_z2
  network: cf2
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.large
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: large_z1
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.large
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: large_z2
  network: cf2
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.large
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: runner_z1
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.large
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: runner_z2
  network: cf2
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.medium
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: router_z1
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.medium
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: router_z2
  network: cf2
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.small
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: small_errand
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    instance_type: m1.large
  env:
    bosh:
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0
  name: xlarge_errand
  network: cf1
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000

